<?php
	define ("DB_SERV", DATU-BASEAREN URL-A);
	define ("DB_USER", DATU-BASEAREN ERABILTZAILE-IZENA);
	define ("DB_PASS", DATU-BASEAREN PASAHITZA);
	define ("DB_NAME", DATU-BASEAREN IZENA);
?>
